### PR TITLE
Unload global player when leaving edit view

### PR DESCRIPTION
**Pull request by farski**

### CODE REVIEW

**Comment by chrisrhoden** [comment]
I don't think you should unload unless the player is playing a preview. It is possible to imagine navigating here while listening to something

**Comment by chrisrhoden** [comment]
Also please write a test

**Comment by chrisrhoden** [comment]
I think you should also look into using the state leave callback instead of the controller unload

**Comment by chrisrhoden** [comment]
@farski bump

**Comment by farski** [comment]
Deals with #256

**Pull request merged**
