### PR TITLE
Refactor stylesheets

### PR DESCRIPTION
**Pull request by farski**
Unless I'm reading this wrong, and I very well could be, this about halves the size on the wire for the css and render time. There could be other other differences between alpha and beta that account for some of that, though.

### CODE REVIEW

**Comment by chrisrhoden** [comment]
@farski I'm not sure I remember where we left this completely. Do you want to do a review at some point or would you rather I just do another pass with a fine toothed comb and pick some nits?

**Comment by farski** [comment]
I feel like we could nitpick this to death. If we want to double check for any serious issues that are blockers that's fine, but another round of fairly inconsequential stuff or things that can be dealt with later doesn't seem necessary since this merge is holding up several other branches at this point. And since this has effectively been deployed to alpha for extended periods by now, I don't think there are any major issues that we haven't found yet and dealt with.

**Comment by chrisrhoden** [comment]
@farski Okay. I expect there will be some merge conflicts, would you feel comfortable taking those on or would you rather I do my best to take care of it?

**Comment by farski** [comment]
@chrisrhoden I'm going to try, I'll let you know if I run into any problems

**Comment by chrisrhoden** [comment]
@farski just going to deploy the merged thing to staging and give it a once over

**Comment by chrisrhoden** [comment]
@farski we lost the loading indicators in the "recent stories" section of the account sidebar on the story page. Will file a jira ticket

**Pull request merged**
